// //局部样式
// @Extend(Image) function imageStyle(){
//   .width('100%')
//   .margin(15)
//   .borderRadius(20)
// }
//
// //全局样式
// @Extend(Column) function containerStyle(){
//   .width('100%')
//   .height('100%')
// }
//
// //样式继承扩展
// @Extend(Button) function textStyle(){
//   .fontSize(15)
//   .fontColor(Color.White)
//   .backgroundColor('#36D')
//   .width(80)
//   .borderRadius(40)
// }
//
// export {imageStyle,containerStyle,textStyle};